# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b7519351abb37b0cce34577302d468a9cef3e90d0b91f40c6c87aa42ae7fe1895bb207ebcb59ed7db6a571b9bafb0a2c2d6eb98fc752b0d01f43630cad57409

test:
  secret_key_base: 964f13743f2808e92087b91375cb3cf9ffd05560c644a16a854a757a72aea66582cfbeeabde0ebfc3ed490b9734fe424c25ede3f5a3d7803d0fe67da9bf9838c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
